version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
  nginx:
    container_name: nginx
    links:
      - api
      - web
    restart: always
    build:
      context: packages/nginx
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"

  api:
    container_name: api
    build:
      context: ./packages/api
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - /app/node_modules
      - ./packages/api:/app/api
    links:
      - mongodb
    depends_on:
      - mongodb

  web:
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    container_name: web
    build:
      context: ./packages/web
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./packages/web:/app/web
