version: "3"

services:
  rest-service:
    container_name: rest-service
    build:
      context: ./
      dockerfile: Dockerfile.rest-service
    environment:
      - NODE_ENV=development
    ports:
      - "3001:3001"
    expose:
      - 3001
    volumes:
      - ./node_modules:/scheduler/node_modules
      - ./package.json:/scheduler/package.json
      - ./packages/rest-service:/scheduler/packages/rest-service
    links:
      - mongodb
    depends_on:
      - mongodb

  web-app:
    container_name: web-app
    build:
      context: ./
      dockerfile: Dockerfile.web-app
    ports:
      - "3000:3000"
    expose:
      - 3000
    links:
      - rest-service
    volumes:
      - ./node_modules:/scheduler/node_modules
      - ./package.json:/scheduler/package.json
      - ./packages/web-app:/scheduler/packages/web-app

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
