FROM node:14-alpine

WORKDIR /scheduler

COPY ./package.json ./
COPY ./yarn.lock ./
COPY lerna.json ./

COPY ./packages/web-app/package.json ./packages/web-app/

RUN yarn

COPY ./packages/web-app/ ./packages/web-app/

CMD [ "yarn", "dev:web" ]