version: "3"

services:
  rest-service:
    container_name: rest-service
    build:
      context: ./packages/rest-service
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    ports:
      - "3001:3001"
    expose:
      - 3001
    volumes:
      - ./packages/rest-service:/scheduler/rest-service
    links:
      - mongodb
    depends_on:
      - mongodb

  web-app:
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    container_name: web-app
    build:
      context: ./packages/web-app
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    expose:
      - 3000
    links: 
      - rest-service
    volumes:
      - ./packages/web-app:/scheduler/web-app

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
