apiVersion: v1
kind: Secret
metadata:
  name: api-config
type: Opaque
stringData:
  PORT: "3001"
  DATABASE_URI: "mongodb://mongodb-cluster-ip-service:27017/testdb"
  FIREBASE_PROJECT_ID: __FIREBASE_PROJECT_ID__
  FIREBASE_CLIENT_EMAIL: __FIREBASE_CLIENT_EMAIL__
  FIREBASE_CLIENT_ID: __FIREBASE_CLIENT_ID__
  FIREBASE_PRIVATE_KEY: __FIREBASE_PRIVATE_KEY__
