apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-persistent-volume
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1G
  hostPath:
    path: /tmp/mongodb-persistent-volume
