k-apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-persistent-volume
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1G
  hostPath:
    path: /tmp/mongo-persistent-volume
