apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  volumes:
    - name: mongo-vol
      persistentVolumeClaim:
        claimName: mongo-pvc
  containers:
    - image: mongo
      name: mongodb
      command:
        - mongod
        - "--bind_ip"
        - "0.0.0.0"
      ports:
        - containerPort: 27017
      volumeMounts:
        - name: mongo-vol
          mountPath: /data/db
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 100Mi
