apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-service-app
  template:
    metadata:
      labels:
        app: rest-service-app
    spec:
      containers:
        - image: __DOCKER_REPOSITORY__/__REST_IMAGE_NAME__:__IMAGE_TAG__
          name: scheduler-rest-service-container
          ports:
            - containerPort: 3001
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: rest-config
