# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: rest-service-load-balancer
spec:
  selector:
    app: rest-service-app
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30001
  type: NodePort
