AWSTemplateFormatVersion: 2010-09-09
Description: Infrastructure for the EKS cluster

Parameters:
  ClusterName:
    Type: String
    Description: Name of the EKS cluster
    Default: harvey-eks-cluster

Resources:
  HarveyEKSVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/26

  HarveyEKSInternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: HarveyEKSVPC

  HarveyEKSInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref HarveyEKSVPC
      InternetGatewayId: !Ref HarveyEKSInternetGateway

  HarveyEKSPrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/27
      VpcId: !Ref HarveyEKSVPC
      AvailabilityZone: us-west-2a

  HarveyEKSPublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.32/27
      VpcId: !Ref HarveyEKSVPC
      AvailabilityZone: us-west-2a

  HarveyEKSNATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt HarveyEKSElasticIPAddress.AllocationId
      SubnetId: !Ref HarveyEKSPublicSubnetA

  HarveyEKSElasticIPAddress:
    Type: AWS::EC2::EIP
    Properties:
      Domain: VPC

  HarveyEKSPrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref HarveyEKSVPC

  HarveyEKSPrivateRoute:
    Type: AWS::EC2::Route
    DependsOn: HarveyEKSNATGateway
    Properties:
      RouteTableId: !Ref HarveyEKSPrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref HarveyEKSNATGateway

  HarveyEKSPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref HarveyEKSVPC

  HarveyEKSPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: !Ref HarveyEKSInternetGatewayAttachment
    Properties:
      RouteTableId: !Ref HarveyEKSPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref HarveyEKSInternetGateway

  HarveyEKSPrivateSubnetRouteTableAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref HarveyEKSPrivateSubnetA
      RouteTableId: !Ref HarveyEKSPrivateRouteTable

  HarveyEKSPublicSubnetRouteTableAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref HarveyEKSPublicSubnetA
      RouteTableId: !Ref HarveyEKSPublicRouteTable

  # Cluster
  HarveyEKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      RoleArn: !GetAtt HarveyEKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds:
          - !Ref HarveyEKSPrivateSubnetA
          - !Ref HarveyEKSPublicSubnetA
        EndpointPrivateAccess: true
        EndpointPublicAccess: true

  HarveyEKSClusterNodegroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      AmiType: AL2_x86_64
      CapacityType: ON_DEMAND
      DiskSize: 20
      ClusterName: !Ref ClusterName
      NodegroupName: harvey-eks-cluster-nodegroup
      NodeRole: "arn:aws:iam::527728718473:role/AmazonEKSNodeRole"
      Subnets:
        - !Ref HarveyEKSPrivateSubnetA
        - !Ref HarveyEKSPublicSubnetA
      ScalingConfig:
        DesiredSize: 1
        MaxSize: 1
        MinSize: 1
    DependsOn: HarveyEKSCluster

  HarveyEKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Description: Role to provide access to the EKS cluster
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
        - "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
        - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
        - "arn:aws:iam::aws:policy/AmazonEKSServicePolicy"
        - "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
      RoleName: harvey-eks-cluster-role
